build:
	docker build -t simple .
run:
	docker run --rm simple
tag:
	docker tag simple:1.0 registry.orb.local/simple:1.0
push:
	docker push registry.orb.local/simple:1.0
pull:
	docker pull registry.orb.local/simple:1.0